#!/usr/bin/env node

var colors = require('skilstak-colors')
var le = require('./letters')

var main = function() {
  var letters = ["a","b","c","d","e","f","g","h","i","j","k","l","m","n","o","p","q","r","s","t","u","v","w","x","y","z"]
  var index = Math.floor(Math.random() * letters.length)
  var a = letters[index]
  var A = a.toUpperCase()
  letters.splice(index, 1);
  index = Math.floor(Math.random() * letters.length)
  var b = letters[index]
  var B = b.toUpperCase()
  letters.splice(index, 1);
  index = Math.floor(Math.random() * letters.length)
  var c = letters[index]
  var C = c.toUpperCase()
  letters.splice(index, 1);
  index = Math.floor(Math.random() * letters.length)
  var d = letters[index]
  var D = d.toUpperCase()
  letters.splice(index, 1);
  index = Math.floor(Math.random() * letters.length)
  var e = letters[index]
  var E = e.toUpperCase()
  letters.splice(index, 1);
  index = Math.floor(Math.random() * letters.length)
  var f = letters[index]
  var F = f.toUpperCase()
  letters.splice(index, 1);
  index = Math.floor(Math.random() * letters.length)
  var g = letters[index]
  var G = g.toUpperCase()
  letters.splice(index, 1);
  index = Math.floor(Math.random() * letters.length)
  var h = letters[index]
  var H = h.toUpperCase()
  letters.splice(index, 1);
  index = Math.floor(Math.random() * letters.length)
  var i = letters[index]
  var I = i.toUpperCase()
  letters.splice(index, 1);
  index = Math.floor(Math.random() * letters.length)
  var j = letters[index]
  var J = j.toUpperCase()
  letters.splice(index, 1);
  index = Math.floor(Math.random() * letters.length)
  var k = letters[index]
  var K = k.toUpperCase()
  letters.splice(index, 1);
  index = Math.floor(Math.random() * letters.length)
  var l = letters[index]
  var L = l.toUpperCase()
  letters.splice(index, 1);
  index = Math.floor(Math.random() * letters.length)
  var m = letters[index]
  var M = m.toUpperCase()
  letters.splice(index, 1);
  index = Math.floor(Math.random() * letters.length)
  var n = letters[index]
  var N = n.toUpperCase()
  letters.splice(index, 1);
  index = Math.floor(Math.random() * letters.length)
  var o = letters[index]
  var O = o.toUpperCase()
  letters.splice(index, 1);
  index = Math.floor(Math.random() * letters.length)
  var p = letters[index]
  var P = p.toUpperCase()
  letters.splice(index, 1);
  index = Math.floor(Math.random() * letters.length)
  var q = letters[index]
  var Q = q.toUpperCase()
  letters.splice(index, 1);
  index = Math.floor(Math.random() * letters.length)
  var r = letters[index]
  var R = r.toUpperCase()
  letters.splice(index, 1);
  index = Math.floor(Math.random() * letters.length)
  var s = letters[index]
  var S = s.toUpperCase()
  letters.splice(index, 1);
  index = Math.floor(Math.random() * letters.length)
  var t = letters[index]
  var T = t.toUpperCase()
  letters.splice(index, 1);
  index = Math.floor(Math.random() * letters.length)
  var u = letters[index]
  var U = u.toUpperCase()
  letters.splice(index, 1);
  index = Math.floor(Math.random() * letters.length)
  var v = letters[index]
  var V = v.toUpperCase()
  letters.splice(index, 1);
  index = Math.floor(Math.random() * letters.length)
  var w = letters[index]
  var W = w.toUpperCase()
  letters.splice(index, 1);
  index = Math.floor(Math.random() * letters.length)
  var x = letters[index]
  var X = x.toUpperCase()
  letters.splice(index, 1);
  index = Math.floor(Math.random() * letters.length)
  var y = letters[index]
  var Y = y.toUpperCase()
  letters.splice(index, 1);
  index = Math.floor(Math.random() * letters.length)
  var z = letters[index]
  var Z = z.toUpperCase()
  letters.splice(index, 1);
  console.log(colors.clear + colors.red + "Code:\n" + colors.orange + a+b+c+d+e+f+g+h+i+j+k+l+m+n+o+p+q+r+s+t+u+v+w+x+y+z)
}
main()
