#!/usr/bin/env node

var colors = require('skilstak-colors')
var Letters = {a:"a",b:"b",c:"c",d:"d",e:"e",f:"f",g:"g",h:"h",i:"i",j:"j",k:"k",l:"l",m:"m",n:"n",o:"o",p:"p",q:"q",r:"r",s:"s",t:"t",u:"u",v:"v",w:"w",x:"x",y:"y",z:"z"}

var main = function() {
  var letters = ["a","b","c","d","e","f","g","h","i","j","k","l","m","n","o","p","q","r","s","t","u","v","w","x","y","z"]
  var index = Math.floor(Math.random() * letters.length)
  var a = letters[index]
  Letters.a = a
  Letters.A = a.toUpperCase()
  letters.splice(index, 1);
  index = Math.floor(Math.random() * letters.length)
  var b = letters[index]
  Letters.b = b
  Letters.B = b.toUpperCase()
  letters.splice(index, 1);
  index = Math.floor(Math.random() * letters.length)
  var c = letters[index]
  Letters.c = c
  Letters.C = c.toUpperCase()
  letters.splice(index, 1);
  index = Math.floor(Math.random() * letters.length)
  var d = letters[index]
  Letters.d = d
  Letters.D = d.toUpperCase()
  letters.splice(index, 1);
  index = Math.floor(Math.random() * letters.length)
  var e = letters[index]
  Letters.e = e
  Letters.E = e.toUpperCase()
  letters.splice(index, 1);
  index = Math.floor(Math.random() * letters.length)
  var f = letters[index]
  Letters.f = f
  Letters.F = f.toUpperCase()
  letters.splice(index, 1);
  index = Math.floor(Math.random() * letters.length)
  var g = letters[index]
  Letters.g = g
  Letters.G = g.toUpperCase()
  letters.splice(index, 1);
  index = Math.floor(Math.random() * letters.length)
  var h = letters[index]
  Letters.h = h
  Letters.H = h.toUpperCase()
  letters.splice(index, 1);
  index = Math.floor(Math.random() * letters.length)
  var i = letters[index]
  Letters.i = i
  Letters.I = i.toUpperCase()
  letters.splice(index, 1);
  index = Math.floor(Math.random() * letters.length)
  var j = letters[index]
  Letters.j = j
  Letters.J = j.toUpperCase()
  letters.splice(index, 1);
  index = Math.floor(Math.random() * letters.length)
  var k = letters[index]
  Letters.k = k
  Letters.K = k.toUpperCase()
  letters.splice(index, 1);
  index = Math.floor(Math.random() * letters.length)
  var l = letters[index]
  Letters.l = l
  Letters.L = l.toUpperCase()
  letters.splice(index, 1);
  index = Math.floor(Math.random() * letters.length)
  var m = letters[index]
  Letters.m = m
  Letters.M = m.toUpperCase()
  letters.splice(index, 1);
  index = Math.floor(Math.random() * letters.length)
  var n = letters[index]
  Letters.n = n
  Letters.N = n.toUpperCase()
  letters.splice(index, 1);
  index = Math.floor(Math.random() * letters.length)
  var o = letters[index]
  Letters.o = o
  Letters.O = o.toUpperCase()
  letters.splice(index, 1);
  index = Math.floor(Math.random() * letters.length)
  var p = letters[index]
  Letters.p = p
  Letters.P = p.toUpperCase()
  letters.splice(index, 1);
  index = Math.floor(Math.random() * letters.length)
  var q = letters[index]
  Letters.q = q
  Letters.Q = q.toUpperCase()
  letters.splice(index, 1);
  index = Math.floor(Math.random() * letters.length)
  var r = letters[index]
  Letters.r = r
  Letters.R = r.toUpperCase()
  letters.splice(index, 1);
  index = Math.floor(Math.random() * letters.length)
  var s = letters[index]
  Letters.s = s
  Letters.S = s.toUpperCase()
  letters.splice(index, 1);
  index = Math.floor(Math.random() * letters.length)
  var t = letters[index]
  Letters.t = t
  Letters.T = t.toUpperCase()
  letters.splice(index, 1);
  index = Math.floor(Math.random() * letters.length)
  var u = letters[index]
  Letters.u = u
  Letters.U = u.toUpperCase()
  letters.splice(index, 1);
  index = Math.floor(Math.random() * letters.length)
  var v = letters[index]
  Letters.v = v
  Letters.V = v.toUpperCase()
  letters.splice(index, 1);
  index = Math.floor(Math.random() * letters.length)
  var w = letters[index]
  Letters.w = w
  Letters.W = w.toUpperCase()
  letters.splice(index, 1);
  index = Math.floor(Math.random() * letters.length)
  var x = letters[index]
  Letters.x = x
  Letters.X = x.toUpperCase()
  letters.splice(index, 1);
  index = Math.floor(Math.random() * letters.length)
  var y = letters[index]
  Letters.y = y
  Letters.Y = y.toUpperCase()
  letters.splice(index, 1);
  index = Math.floor(Math.random() * letters.length)
  var z = letters[index]
  Letters.z = z
  Letters.Z = z.toUpperCase()
  letters.splice(index, 1);
  console.log(/*colors.clear + */colors.red + "Code:\n" + colors.orange + a+b+c+d+e+f+g+h+i+j+k+l+m+n+o+p+q+r+s+t+u+v+w+x+y+z)
}

console.log(Letters.a)
main()
console.log(Letters.a)
