#!/usr/bin/env node

var colors = require('skilstak-colors')

var run = function(message){
  final = ""
  if (message.startsWith("#")){
      for (var n = 1; n < message.length; n++){
          final += /*inverse[*/message[n]/*]*/
      }
  } else {
      final += "#"
      for (var n = 0; n < message.length; n++){
          final += /*j[*/message[n]/*]*/
      }
  }
  console.log(final)
}

run("#Hey there my dude")
