#!/usr/bin/env python3

"""Creates a random code that messages will be encoded to"""

import random
import string
import json

def main():
    jsonfile = open('currentcode.js', 'w')
    letters = [ x for x in string.ascii_lowercase ]
    keys = [ x for x in letters ]
    random.shuffle(letters)
    values = [ y for y in letters ]
    code = {}
    for i in range(len(letters)):
        code.update({keys[i]:values[i]})
        code.update({keys[i].title():values[i].title()})
    print(values)
    jsonfile.write("var Letters = " + str(code))

if __name__ == '__main__':
    main()
