#!/usr/bin/env python3

"""Creates a random code that messages will be encoded to"""

import random
import skilstak.colors as colors
import sys

def main():
    letters = ["a","b","c","d","e","f","g","h","i","j","k","l","m","n","o","p","q","r","s","t","u","v","w","x","y","z"]
    with open('currentcode.js', 'w') as pfile:
        print(colors.clear + colors.red + "Code:" + colors.orange)
        pfile.write("var Letters = {")
        for key in "abcdefghijklmnopqrstuvwxyz":
            value = random.choice(letters)
            letters.remove(value)
            sys.stdout.write(value)
            pfile.write(
                    '"' + key + '":"' + value + '","' + key.upper() + '":"' + value.upper() + '",'
                )
        pfile.write('" ":" "}')
        print()

if __name__ == '__main__':
    main()
